spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      filter:
        enabled: true
      transport:
        port: 8719
        #指定sentinel控制台的地址
        dashboard: 127.0.0.1:8858
      eager: true
      datasource:
        ds2:
          nacos:
            data-type: json # 默认提供两种内置的值，分别是 json 和 xml (不填默认是json)
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow #rule-type 配置表示该数据源中的规则属于哪种类型的规则(flow流控，degrade熔断降级，authority，system系统保护, param-flow热点参数限流, gw-flow, gw-api-group)

ribbon:
  #请求连接的超时时间
  ConnectTimeout: 5000
  #请求处理/响应的超时时间
  ReadTimeout: 5000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 0
  #当前实例的重试次数
  MaxAutoRetries: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
